stages:
  - build

.build:
  image: ubuntu:focal
  stage: build
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt-get -y install libpolkit-gobject-1-dev policykit-1 libglibd-2.0-dev libssl-dev ldc git build-essential gir-to-d libgirepository1.0-dev libdbus-1-dev dbus-x11 python3-dbusmock gettext python3-pip
    - pip3 install meson ninja
    - git clone https://gitlab.alpinelinux.org/alpine/abuild
    - git clone https://gitlab.alpinelinux.org/alpine/apk-tools
    - git clone https://gitlab.alpinelinux.org/Cogitri/apk-toolsd
    - git clone https://gitlab.alpinelinux.org/Cogitri/polkit-d
    - git clone https://github.com/Cogitri/openssl
    - cd abuild && sed 's|bin/ash|bin/bash|g' -i *.in && make install
    - cd ../apk-tools && make CFLAGS="-Wno-error" LUAAPK="" SCDOC="" install
    - cd ../openssl && git checkout meson && meson build && ninja -C build install
    - cd ../apk-toolsd && meson build && ninja -C build install
    - cd ../polkit-d && meson build && ninja -C build install
    - cd ../ && meson build && env LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu ninja -C build test

build-ldc:
  extends: .build


build-ldc-sanitizer:
  extends: .build
  variables:
     DFLAGS: "-fsanitize=address -g -disable-fp-elim"
     ASAN_OPTIONS: "detect_leaks=0" # disable for now
